src/products/urls.py
from django.conf.urls import url

from .views import (
  ProductDetailView,
  ProductListView,
  TagListView,
  TagDetailView,
  )

# app_name = 'utpshare'

# urlpatterns = [
#   path('', ProductListView.as_view(), name='products'),
#   # path('<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
#   path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
# ]


urlpatterns = [
  url(r'^$', ProductListView.as_view(), name='products'),
  url(r'^detail/(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='product_detail'),
  url(r'^tags/$', TagListView.as_view(), name='tags'),
  url(r'^tags/(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='tag_detail'),
]

src/user/urls.py
from django.conf.urls import url, include

from .views import UserDashboardView, OrderList, OrderDetail


urlpatterns = [
    url(r'^$', UserDashboardView.as_view(), name='user_dashboard'),
    url(r'^orders/$', OrderList.as_view(), name='orders'),
    url(r'^orders/(?P<pk>\d+)/$', OrderDetail.as_view(), name='order_detail'),
]

src/utpshare/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include

from products.views import ProductSearchListView, ProductListRedirectView
from user.views import UserDashboardView
from carts.views import CartView, ItemCountView, CheckoutView, CheckoutFinalView
from orders.views import UserAddressCreateView


urlpatterns = [
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^results/', ProductSearchListView.as_view(), name='product_search_list'),
    url(r'^$', ProductListRedirectView.as_view()),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^seller/', include('seller.urls', namespace='seller')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^cart/count/$', ItemCountView.as_view(), name='item_count'),
    url(r'^checkout/$', CheckoutView.as_view(), name='checkout'),
    url(r'^checkout/add_address/$', UserAddressCreateView.as_view(), name='user_address_create'),
    url(r'^checkout/final/$', CheckoutFinalView.as_view(), name='checkout_final'),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/sales/models.py
from django.db import models
from carts.models import CartItem
from seller.models import SellerAccount
from orders.models import Order
# Create your models here.

SALE_STATUS_CHOICES = (
  ('pending', 'Pending'),
  ('approved', 'Approved'),
  ('delivered', 'Delivered'),
)

class Sale(models.Model):
  seller = models.ForeignKey(SellerAccount, on_delete=models.CASCADE)
  timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
  order = models.ManyToManyField(Order)
  status = models.CharField(max_length=120, choices=SALE_STATUS_CHOICES, default='pending')

  def __str__(self):
    return str(self.id)

  def get_seller_item_list(self):
    seller = self.seller
    seller_item_list = self.order.first().cart.cartitem_set.filter(seller=seller)
    return seller_item_list

  def compute_sale_total(self):
    seller_item_list = self.get_seller_item_list()
    sale_total = 0
    for seller_item in seller_item_list:
      sale_total += seller_item.line_total
    return sale_total

src/user/models.py
from django.db import models

# Create your models here.

src/user/views.py
import random

from django.views.generic import View
from django.views.generic.detail import DetailView
from django.shortcuts import render

# Create your views here.

from utpshare.mixins import LoginRequiredMixin
from products.models import Product
from orders.models import Order

class UserDashboardView(View):
  def get(self, request, *args, **kwargs):
    tag_views = None
    products = None
    top_tags = None
    owned = None
    try:
      tag_views = request.user.tagview_set.all().order_by("-count")[:5]
    except:
      pass

    if tag_views:
      top_tags = [x.tag for x in tag_views]
      products = Product.objects.filter(tags__in=top_tags)
      products=products.distinct()
      products = sorted(products, key= lambda x: random.random())
      products = products[:8]

    #  ORDER LIST
    order_id = self.request.session.get("order_id")
    try:
      user_orders = Order.objects.filter(user=request.user).filter(status="completed").order_by("-time_created")[:2]
    except:
      user_orders = None

    context = {
      "products": products,
      "top_tags": top_tags,
      "user": request.user,
      "order_id": order_id,
      "user_orders": user_orders,
    }
    return render(request, "user/dashboard.html", context)



class OrderList(LoginRequiredMixin, View):
  def get(self, request, *args, **kwargs):
    order_id = self.request.session.get("order_id")
    try:
      user_orders = Order.objects.filter(user=request.user).order_by("-time_created")
    except:
      user_orders = None

    context = {
      "user_orders": user_orders,
      "order_id": order_id,
    }
    return render(request, "user/order_list.html", context)


class OrderDetail(DetailView):
  model = Order
  template_name = "user/order_detail.html"

  def dispatch(self, request, *args, **kwargs):
    obj = self.get_object()
    if obj.user == request.user and request.user is not None:
      return super(OrderDetail, self).dispatch(request, *args, **kwargs)
    else:
      raise Http404

src/templates/user/dashboard.html
{% extends 'base.html' %}

{% block style %}
.orderls-outer-content {
  background-color: #fff;
  padding: 15px;
  margin-top: 5px;
}
.orderls-header {
  background-color: #f2f2f2;
  padding: 10px 5px 10px 5px;
  margin-bottom: 5px;
}
.orderls-content {
  background-color: #fff;
  padding: 15px;
}
.mb-orderls-content {
  display:none;
}
.mb-orderls-content-header {
  margin: 0 0 10px 0;
  border-top: 1px solid #c7c7c7; 
}

@media screen and (max-width: 800px) {
  .mb-orderls-content {
    display:initial;
  }
  .hideContent {
    display:none;
  }
}

a:link, a:hover, a:visited, a:active {
  text-decoration: none;
}

.tag-style a:link, .tag-style a:hover, .tag-style a:visited, .tag-style a:active {
  color: white;
}

.tag-style {
  background: #058;
  color:#fff;
  padding: 1px 8px;
  border-radius: 10px;
  display: inline-block;
  margin: 3px 1px;
}
{% endblock %}

{% block content %}
<div class="title-banner">{{ user }}'s Dashboard</div>
<div class="container">
  {% if user_orders %}
    <h4>Recent Orders</h4>
    {% include "user/order_list_template.html" %}
    <a href="{% url 'user:orders' %}" class="btn btn-default btn-block">View All Orders</a>
  {% endif %}

  {% if products %}
    <h4 style="margin-top:40px;">Suggested Products</h4>
    <div class="tn-set-container">
      {% for product in products %}
        {% include "products/product_thumbnail.html" with product=product %}
      {% endfor %}
    </div>
  {% else %}
    <div class="text-center">
      <h4 style="margin-top:40px;">Just getting started?</h4>
      <a href="{% url 'products:products' %}">Explore</a>
    </div>
  {% endif %}

  {% if top_tags %}
    <div style="margin:40px 0 100px;">
      <h4>Top Tags</h4>
      {% for tag in top_tags %}
        <div class="tag-style"><a href="{{ tag.get_absolute_url }}">{{ tag }}</a></div>
      {% endfor %}
    </div>
  {% endif %}
</div>

{% endblock %}

src/templates/user/order_detail.html
{% extends "base.html" %}



{% block content %}
<div class="container">
{% include "orders/order_summary.html" with order=order %}
</div>
{% endblock %}

src/templates/user/order_list.html
{% extends "base.html" %}

{% block style %}
.orderls-outer-content {
  background-color: #fff;
  padding: 15px;
  margin-top: 5px;
}
.orderls-header {
  background-color: #f2f2f2;
  padding: 10px 5px 10px 5px;
  margin-bottom: 5px;
}
.orderls-content {
  background-color: #fff;
  padding: 15px;
}
.mb-orderls-content {
  display:none;
}
.mb-orderls-content-header {
  margin: 0 0 10px 0;
  border-top: 1px solid #c7c7c7; 
}

@media screen and (max-width: 800px) {
  .mb-orderls-content {
    display:initial;
  }
  .hideContent {
    display:none;
  }
}

a:link, a:hover, a:visited, a:active {
  color: #000;
  text-decoration: none;
}
{% endblock %}

{% block content %}
<div class="container">
  <h2>ORDERS</h2>
  {% include "user/order_list_template.html" %}
</div>
{% endblock %}

src/templates/user/order_list_template.html
<div class="orderls-outer-content">
  <div>
    <div class="orderls-header hideContent">
      <div class="row">
        <div class="col-sm-8">Product</div>
        <div class="col-sm-2">Seller</div>
        <div class="col-sm-2">Order Status</div>
      </div>
    </div>

    {% for user_order in user_orders %}
      {% if user_order.status == "completed" %}
        <div>
          <div class="orderls-header">
            <div class="row">
              <div class="col-sm-6">
                <strong>Order ID:</strong> <a href="{% url 'user:order_detail' pk=user_order.id %}">{{ user_order.order_id }}</a><br>
                <strong>Date:</strong> {{ user_order.sale_set.first.timestamp|date:"d M Y (D) g:i a" }}
              </div>
              <div class="col-sm-6">
                <strong>Amount:</strong> RM {{ user_order.order_total }} <br>
                <strong>Delivery:</strong> RM {{ user_order.cart.delivery_fee }}
              </div>
            </div>
          </div>

          <div class="mb-orderls-content">
            {% for sale in user_order.sale_set.all %}
              <div class="mb-orderls-content-header">
                Items from <strong>{{ sale.seller }}</strong> are <strong>{{ sale.status }}</strong>.
              </div>
              {% for seller_item in sale.get_seller_item_list %}
                {% include "seller/item_detail_template.html" %}
              {% endfor %}
            {% endfor %}
          </div>

          <div class="orderls-content hideContent">
            {% for sale in user_order.sale_set.all %} 
            <div class="row">
              <div class="col-sm-8">
                {% for seller_item in sale.get_seller_item_list %}
                  {% include "seller/item_detail_template.html" %}
                {% endfor %}
              </div>
              <div class="col-sm-2">
                {{ sale.seller }} 
              </div>
              <div class="col-sm-2">
                {{ sale.status }} 
              </div>
            </div>
            {% endfor %}
          </div>

        </div>
      {% else %}
        {% if order_id == user_order.id %}
          <div style="text-align:center; padding: 10px; background-color:#f2f2f2; margin:10px 0;">
            You order <strong>#{{ user_order.order_id }} ({{ user_order.time_created|timesince }} ago)</strong> is yet to be completed.<br/>
            Proceed to complete this order?<br/><br/>
            <a href="{% url 'checkout' %}">
              <button class="btn btn-warning btn-sm">Proceed</button>
            </a>
            <form method="get" action="{% url 'cart' %}" style="display:inline;">
              <input type="hidden" name="delete_order" value="True">
              <button type="submit" 
                      class="btn btn-danger btn-sm">Forfeit
              </button>
            </form>
          </div>
        {% endif %}
      {% endif %}
    {% empty %}
      <p class="text-center">No orders yet.</p>
    {% endfor %}

  </div>
</div>