src/products/urls.py
from django.conf.urls import url

from .views import (
  ProductDetailView,
  ProductListView,
  TagListView,
  TagDetailView,
  )

# app_name = 'utpshare'

# urlpatterns = [
#   path('', ProductListView.as_view(), name='products'),
#   # path('<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
#   path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
# ]


urlpatterns = [
  url(r'^$', ProductListView.as_view(), name='products'),
  url(r'^detail/(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='product_detail'),
  url(r'^tags/$', TagListView.as_view(), name='tags'),
  url(r'^tags/(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='tag_detail'),
]

src/seller/urls.py
from django.conf.urls import url
from seller import views

from .views import (
        SellerDashboard,
        SellerProductListView,
        SellerProductDetailRedirectView,
        SellerSalesListView,
        ProductCreateView,
        ProductUpdateView,
        )

# app_name = 'utpshare'

urlpatterns = [
  url(r'^$', SellerDashboard.as_view(), name='dashboard'),
  url(r'^sales/$', SellerSalesListView.as_view(), name='sales_list'),
  url(r'^sales/(?P<pk>\d+)/$', views.sale_detail, name='modal_sale_detail'),

  url(r'^products/$', SellerProductListView.as_view(), name='product_list'),
  url(r'^products/add/$', ProductCreateView.as_view(), name='product_create'),
  url(r'^products/(?P<slug>[\w-]+)/edit/$', ProductUpdateView.as_view(), name='product_update'),
  
  url(r'^products/modal_add/$', views.product_create, name='modal_product_create'),
  url(r'^products/(?P<slug>[\w-]+)/modal_edit/$', views.product_update, name='modal_product_update'),
  url(r'^products/(?P<slug>[\w-]+)/modal_delete/$', views.product_delete, name='modal_product_delete'),
  url(r'ajax/load-subcategories/', views.load_subcategories, name='ajax_load_subcategories')
  
]


'''
The urlpattern below is going to break any url which comes after it
and has the pattern "products/*char*/
Ex. products/add
Ex.2 products/modal_add
WHY? Because slug can arguably be any word possible, so django will search for it,
hence break any further patterns

DANGER! DON'T USE THIS PATTERN!
path('products/<slug:slug>/', SellerProductDetailRedirectView.as_view()),
'''

src/user/urls.py
from django.conf.urls import url, include

from .views import UserDashboardView, OrderList, OrderDetail


urlpatterns = [
    url(r'^$', UserDashboardView.as_view(), name='user_dashboard'),
    url(r'^orders/$', OrderList.as_view(), name='orders'),
    url(r'^orders/(?P<pk>\d+)/$', OrderDetail.as_view(), name='order_detail'),
]

src/utpshare/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include

from products.views import ProductSearchListView, ProductListRedirectView
from user.views import UserDashboardView
from carts.views import CartView, ItemCountView, CheckoutView, CheckoutFinalView
from orders.views import UserAddressCreateView


urlpatterns = [
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^results/', ProductSearchListView.as_view(), name='product_search_list'),
    url(r'^$', ProductListRedirectView.as_view()),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^seller/', include('seller.urls', namespace='seller')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^cart/count/$', ItemCountView.as_view(), name='item_count'),
    url(r'^checkout/$', CheckoutView.as_view(), name='checkout'),
    url(r'^checkout/add_address/$', UserAddressCreateView.as_view(), name='user_address_create'),
    url(r'^checkout/final/$', CheckoutFinalView.as_view(), name='checkout_final'),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block head_title %}utpshare{% endblock %}</title>

    {% include 'head_css.html' %}

    <style>
    {% block style %}
    {% endblock %}
    </style>

  </head>


  <body>
    {% include 'navbar.html' %}

    {% block jumbotron %}
    {% endblock %}


    {% block content %}
    {% endblock %}


    {% include "javascript.html" %}
    
    <script>
    
      {% block jquery %}
      {% endblock %}
    </script> 
    
      {% block javascript %}
      {% endblock %}
    
  </body>

</html>

src/templates/custom_clearable_file_input.html
<!-- DJANGO WIDGET TWEAK -->
<!-- ONLY COMPATIBLE WITH DJANGO >=1.11 -->
<!-- can be used as custom input template -->

{% if widget.is_initial %}
<!--   <span>{{ widget.initial_text }}</span>: <a href="{{ widget.value.url }}">{{ widget.value }}</a>
  {% if not widget.required %}
    <input type="checkbox" name="{{ widget.checkbox_name }}" id="{{ widget.checkbox_id }}"/>
    <label for="{{ widget.checkbox_id }}">{{ widget.clear_checkbox_label }}</label>
  {% endif %} -->
  <span><b>{{ widget.input_text }}</b></span>:
{% endif %}
<input type="{{ widget.type }}" name="{{ widget.name }}"{% include "templates/django/forms/widgets/attrs.html" %}/>

src/templates/form_model.html
<!-- DJANGO CUSTOM FORM -->
<!-- can be used as an alternative to crispy form -->
<!-- {% include "form_model.html" with form=form %} -->

{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

src/templates/head_css.html
{% load staticfiles %}

<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">


<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">
<link href="{% static 'css/custom.css' %}" rel="stylesheet">

src/templates/javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- IMAGE UPLOAD -->
<script src="{% static 'js/jquery-ui.js' %}"></script> 
<!-- AJAX CSRF HANDLER -->
<script src="{% static 'js/django.csrf.js' %}"></script>
<!-- CUSTOM JS -->
<script src="{% static 'js/custom.js' %}"></script>

<script>
  function updateCartItemCount(){
    var badge = $("#cart-count-badge");
    $.ajax({
      type:"GET",
      url: "{% url 'item_count' %}",
      success: function(data){
        badge.text(data.count);
      },
      error: function(response, error){
        console.log(response)
        console.log(error)
      }
    })
  }

  $(document).ready(function(){
    updateCartItemCount();
  })
</script>

src/templates/navbar.html
{% load staticfiles %}

<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" style="font-family: arial;" href='{% url "products:products" %}'>utpshare</a>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <form class="navbar-form navbar-left" method="GET" role="search" action='{% url "product_search_list" %}'>
          <div class="input-group">
            <input type="text" class="form-control" style="font-family: roboto;" placeholder="Search for products" name="q" value="{{ request.GET.q }}">
<!--             <div class="input-group-btn">
              <button type="submit" class="btn btn-default"><i class="fa fa-search" aria-hidden="true"></i></button>
            </div> -->
          </div>
        </form>
      </ul>


      <ul class="nav navbar-nav navbar-right">
      <li>
        <a href="{% url 'cart' %}"><i class="fa fa-shopping-cart fa-navbar-cart"></i> <span id="cart-count-badge" class="badge">{{ request.session.cart_item_count }}</span></a>
      </li>

      {% if request.user.is_authenticated %}
        <li><a href='{% url "user:orders" %}'>Orders</a></li>
        <li><a href='{% url "seller:dashboard" %}'>Account</a></li>
        <li><a href='{% url "auth_logout" %}'>Logout</a></li>
      {% else %}
        <li><a href='{% url "registration_register" %}'>Register</a></li>
      {% endif %}

      {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
        <li class="dropdown">
          <a href='#' class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Login <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
              <form class='navbar-form' method='POST' action='{% url "auth_login" %}'>{% csrf_token %}
                  <div class='form-group'>
                      <input type='text' class='form-control' name='username' placeholder='Username' /> 
                  </div>
                  <div class='form-group'>
                      <input type='password' class='form-control' name='password' placeholder='Password' />
                  </div>
                  <button type='submit' class='btn btn-default btn-block'>Login</button>
              </form> 
              <p class="text-center"><a href='{% url "auth_password_reset" %}'>Forgot password?</a></p>
          </ul>
        </li>
      {% endif %}

      </ul>

    </div><!--/.nav-collapse -->
  </div>
</nav>