src/seller/urls.py
from django.conf.urls import url
from seller import views

from .views import (
        SellerDashboard,
        SellerProductListView,
        SellerProductDetailRedirectView,
        SellerSalesListView,
        ProductCreateView,
        ProductUpdateView,
        )

# app_name = 'utpshare'

urlpatterns = [
  url(r'^$', SellerDashboard.as_view(), name='dashboard'),
  url(r'^sales/$', SellerSalesListView.as_view(), name='sales_list'),
  url(r'^sales/(?P<pk>\d+)/$', views.sale_detail, name='modal_sale_detail'),

  url(r'^products/$', SellerProductListView.as_view(), name='product_list'),
  url(r'^products/add/$', ProductCreateView.as_view(), name='product_create'),
  url(r'^products/(?P<slug>[\w-]+)/edit/$', ProductUpdateView.as_view(), name='product_update'),
  
  url(r'^products/modal_add/$', views.product_create, name='modal_product_create'),
  url(r'^products/(?P<slug>[\w-]+)/modal_edit/$', views.product_update, name='modal_product_update'),
  url(r'^products/(?P<slug>[\w-]+)/modal_delete/$', views.product_delete, name='modal_product_delete'),
  url(r'ajax/load-subcategories/', views.load_subcategories, name='ajax_load_subcategories')
  
]


'''
The urlpattern below is going to break any url which comes after it
and has the pattern "products/*char*/
Ex. products/add
Ex.2 products/modal_add
WHY? Because slug can arguably be any word possible, so django will search for it,
hence break any further patterns

DANGER! DON'T USE THIS PATTERN!
path('products/<slug:slug>/', SellerProductDetailRedirectView.as_view()),
'''

src/user/urls.py
from django.conf.urls import url, include

from .views import UserDashboardView, OrderList, OrderDetail


urlpatterns = [
    url(r'^$', UserDashboardView.as_view(), name='user_dashboard'),
    url(r'^orders/$', OrderList.as_view(), name='orders'),
    url(r'^orders/(?P<pk>\d+)/$', OrderDetail.as_view(), name='order_detail'),
]

src/utpshare/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include

from products.views import ProductSearchListView, ProductListRedirectView
from user.views import UserDashboardView
from carts.views import CartView, ItemCountView, CheckoutView, CheckoutFinalView
from orders.views import UserAddressCreateView


urlpatterns = [
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^results/', ProductSearchListView.as_view(), name='product_search_list'),
    url(r'^$', ProductListRedirectView.as_view()),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^seller/', include('seller.urls', namespace='seller')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^cart/count/$', ItemCountView.as_view(), name='item_count'),
    url(r'^checkout/$', CheckoutView.as_view(), name='checkout'),
    url(r'^checkout/add_address/$', UserAddressCreateView.as_view(), name='user_address_create'),
    url(r'^checkout/final/$', CheckoutFinalView.as_view(), name='checkout_final'),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from seller.models import SellerAccount


from django_resized import ResizedImageField
import tagulous.models

# Create your models here.

class ProductManager(models.Manager):
  def get_related(self, instance):
    products = self.get_queryset().filter(category = instance.category).exclude(id=instance.id)
    return products

class Product(models.Model):
  seller = models.ForeignKey(SellerAccount, on_delete=models.CASCADE)
  title = models.CharField(max_length=50)
  slug = models.SlugField(blank=True, unique=True)
  description = models.TextField()
  price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
  sale_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
  stock_count = models.PositiveSmallIntegerField(default=1)
  category = models.ForeignKey('Category', blank=True, null=True, on_delete=models.CASCADE)
  subcategory = models.ForeignKey('Subcategory', blank=True, null=True, on_delete=models.CASCADE)
  timestamp = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
  tags = tagulous.models.TagField(to="Tag", null=True, blank=True)

  objects = ProductManager()

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse("products:product_detail", kwargs={"slug": self.slug})

  def get_edit_url(self):
    return reverse("seller:product_update", kwargs={"slug": self.slug})

  def get_image_url(self):
    img = self.productimage_set.first()
    if img:
      return img.image.url
    else:
      return '/static/img/default_image.png'

  def get_html_price(self):
    if self.sale_price is not None:
      html_text = "<span class='sale-price'>%s</span>&emsp;<span class='og-price small'>%s</span>"\
        %(self.sale_price, self.price)
    else:
      html_text = "<span class='price'>%s</span>" %(self.price)
    return mark_safe(html_text) 

  def add_to_cart(self):
    return "%s?item_slug=%s&qty=1" %(reverse("cart"), self.slug)

  def remove_from_cart(self):
    return "%s?item_slug=%s&qty=1&delete_item=True" %(reverse("cart"), self.slug)

def create_slug(instance, new_slug=None):
  # 1st time coming in
  slug = slugify(instance.title)
  # 2nd time coming in
  if new_slug is not None:
    slug = new_slug

  # To check if this slug is unique
  # if slug exists, create a new slug by appending its id to it
  qs = Product.objects.filter(slug=slug)
  exists = qs.exists()
  if exists:
    # qs.first().id is used coz instance not saved yet and instance.id not created
    new_slug = "%s-%s" %(slug, qs.first().id)
    # return a fx so that the loop repeats itself again
    return create_slug(instance, new_slug=new_slug)

  return slug 

def product_pre_save_receiver(sender, instance, *args, **kwargs):
  if not instance.slug:
    instance.slug = create_slug(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)


class Tag(tagulous.models.TagModel):
  class TagMeta:
    force_lowercase = True
    max_count = 10
    get_absolute_url=lambda tag: reverse(
            'products:tag_detail', kwargs={'slug': tag.slug}
        )



# Product Images
def image_upload_to(instance, filename):
  title = instance.product.title
  slug = slugify(title)
  basename, file_extension = filename.split(".")
  new_filename = "%s.%s" %(slug, file_extension)
  return "products/%s/%s" %(slug, new_filename)


import PIL
from PIL import Image
from django.utils.six import StringIO


class ProductImage(models.Model):
  product = models.ForeignKey(Product, on_delete=models.CASCADE)
  image = ResizedImageField(size=[700, 500], upload_to=image_upload_to, blank=True, null=True)
  # size[w, h]

  def __str__(self):
    return self.product.title

  @property
  def image_url(self):
    if self.image and hasattr(self.image, 'url'):
      return self.image.url
    else:
      return '/static/img/default_image.png'


class Category(models.Model):
  title = models.CharField(max_length=50, unique=True)
  slug = models.SlugField(blank=True, unique=True)
  parent_category = models.ForeignKey('self', null=True, blank=True)

  def __str__(self):
    return self.title

def category_pre_save_receiver(sender, instance, *args, **kwargs):
  if not instance.slug:
    instance.slug = slugify(instance.title)

pre_save.connect(category_pre_save_receiver, sender=Category)

class Subcategory(models.Model):
  title = models.CharField(max_length=50, unique=True)
  slug = models.SlugField(blank=True, unique=True)
  category = models.ForeignKey(Category)
  
  def __str__(self):
    return self.title

def subcategory_pre_save_receiver(sender, instance, *args, **kwargs):
  if not instance.slug:
    instance.slug = slugify(instance.title)

pre_save.connect(subcategory_pre_save_receiver, sender=Subcategory)

src/seller/models.py
from django.conf import settings
from django.db import models


class SellerAccount(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  active = models.BooleanField(default=False)
  timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

  def __str__(self):
    return str(self.user.username)

src/seller/forms.py
from django import forms


class NewSellerForm(forms.Form):
  agree = forms.BooleanField(label='Agree to Terms', widget=forms.CheckboxInput)

src/templates/seller/item_detail_template.html
<div class="two-col-bar modal-seller-item-list">
  <div class="two-col-bar-left">
    <p>{{ seller_item.item.title }}<br/>
      <small><em>RM {{ seller_item.item.price }} x {{ seller_item.quantity }} = {{ seller_item.line_total }}</em></small>
    </p>
  </div>
  <div class="two-col-bar-right">
    <div class="sm-tn-img-frame">
      <img class="tn-img" src="{{ seller_item.item.get_image_url }}" />
    </div>
  </div>
</div>

src/templates/seller/mb_partial_product_list.html
{% for product in products %} 
  <div class="two-col-bar mb-product-list-item">
    <div class="two-col-bar-left">
      <div class="mb-product-title"><a href='{{ product.get_absolute_url }}'>{{ product.title|truncatechars:50 }}</a></div>
      <button type="button"
              class="btn btn-warning btn-sm js-update-product"
              data-url="{% url 'seller:modal_product_update' product.slug %}">
        <span class="glyphicon glyphicon-pencil"></span> Edit
      </button>
      <button type="button"
              class="btn btn-danger btn-sm js-delete-product"
              data-url="{% url 'seller:modal_product_delete' product.slug %}">
        <span class="glyphicon glyphicon-trash"></span> Delete
      </button>
    </div>
    <div class="two-col-bar-right">
      <a href='{{ product.get_absolute_url }}'><img src='{{ product.get_image_url }}' style='max-width:100px; max-height: 100px;'/></a>
    </div>
  </div>
{% endfor %}

src/templates/seller/partial_product_create.html
{% load widget_tweaks %}
{% load crispy_forms_tags %}

<form method="post" action="{% url 'seller:modal_product_create' %}" class="js-product-create-form" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new product</h4>
  </div>
  <div class="modal-body">
    {% include 'seller/partial_product_form.html' %}
<!--     {% crispy image_form %} -->
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create product</button>
  </div>
</form>

src/templates/seller/partial_product_delete.html
<form method="post" action="{% url 'seller:modal_product_delete' product.slug %}" class="js-product-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm product deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the product <strong>{{ product.title }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete product</button>
  </div>
</form>

src/templates/seller/partial_product_list.html
{% for product in products %} 
  <tr>
    <td class="col-sm-3"><a href='{{ product.get_absolute_url }}'>{{ product.title|truncatechars:50 }}</td>
    <td class="col-sm-2 text-center"><a href='{{ product.get_absolute_url }}'><img src='{{ product.get_image_url }}' style='max-width:100px; max-height: 100px;'/></a></td>
    <td class="col-sm-1"><b> {{ product.price }}</b></td>
    <td class="col-sm-2"> {{ product.tags }}</td>
    <td class="col-sm-2">{{ product.timestamp|date:"D, M d" }}</td>
    <td class="col-sm-2">
      <button type="button"
              class="btn btn-warning btn-sm js-update-product"
              data-url="{% url 'seller:modal_product_update' product.slug %}">
        <span class="glyphicon glyphicon-pencil"></span> Edit
      </button>
      <button type="button"
              class="btn btn-danger btn-sm js-delete-product"
              data-url="{% url 'seller:modal_product_delete' product.slug %}">
        <span class="glyphicon glyphicon-trash"></span> Delete
      </button>
    </td>
  </tr>
{% empty %}
  <tr>
    <td colspan="5" class="text-center bg-warning">No products yet.</td>
  </tr>
{% endfor %}

src/templates/seller/partial_product_update.html
{% load widget_tweaks %}
{% load crispy_forms_tags %}

<form method="post" action="{% url 'seller:modal_product_update' form.instance.slug %}" class="js-product-update-form" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update product</h4>
  </div>
  <div class="modal-body">
    <!-- {% crispy form %} -->
    {% include 'seller/partial_product_form.html' %}
<!--     {% crispy image_form %} -->
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update product</button>
  </div>
</form>

src/templates/seller/product_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block style %}
/***********************
  CUSTOM BTN
************************/
.btn {
    padding: 14px 24px;
    border: 0 none;
    font-weight: 700;
    letter-spacing: 1px;
    text-transform: uppercase;
    background: 0 none;
}
.btn:focus, .btn:active:focus, .btn.active:focus {
    outline: 0 none;
}
/***********************
  CUSTOM BUTTON PRIMARY
************************/
.btn-primary {
    background: #0099cc;
    color: #fff;
}
.btn-primary:hover, .btn-primary:focus, .btn-primary:active, .btn-primary.active, .open > .dropdown-toggle.btn-primary {
    background: #33a6cc;
}
.btn-primary:active, .btn-primary.active {
    background: #007299;
    box-shadow: none;
}
.btn.outline {
    background: none;
    padding: 12px 22px;
}
.btn-primary.outline {
    border: 2px solid #0099cc;
    color: #0099cc;
}
.btn-primary.outline:hover, .btn-primary.outline:focus, .btn-primary.outline:active, .btn-primary.outline.active, .open > .dropdown-toggle.btn-primary {
    color: #33a6cc;
    border-color: #33a6cc;
    background: #e7e7e7;
}
.btn-primary.outline:active, .btn-primary.outline.active {
    border-color: #007299;
    color: #007299;
    box-shadow: none;
    background: #e7e7e7;
}
/***********************
  CUSTOM BUTTON DEFAULT
************************/
.btn-default {
    background: #f8f8f8;
    color: #000;
}
.btn-default:hover, .btn-default:focus, .btn-default:active, .btn-default.active, .open > .dropdown-toggle.btn-default {
  background: #f8f8f8;
}
.btn-default:active, .btn-default.active {
    background: #f4f4f4 !important;
}
{% endblock %}

<script>
{% block jquery %}
var form_count = {{ product_image_formset.total_form_count }};

function cloneForm(selector, prefix) {
    form_count++;
    var newElement = $(selector).clone(true);
    var form_index = newElement.find('input').eq(1).attr('name').split('-')[1];
    newElement.find(':input').each(function() {
        var name = $(this).attr('name').replace('-' + form_index + '-','-' + (form_count-1) + '-');      
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id}).val(''); 
    });
    newElement.find('label').each(function() {
        var newFor = $(this).attr('for').replace('-' + form_index + '-','-' + (form_count-1) + '-');
        $(this).attr('for', newFor);
    });
    newElement.find('img').each(function() {
        var newId = $(this).attr('id').replace('-' + form_index + '-','-' + (form_count-1) + '-');
        var src = '#';
        $(this).attr({'id': newId, 'src': src});
    });
    $('#id_' + prefix + '-TOTAL_FORMS').val(form_count);
    //dynamically adding csrf token to the new form added
    var csrf = $('<input/>')
                  .attr("type", "hidden")
                  .attr("name", "csrfmiddlewaretoken")
                  .attr("value", "{{csrf_token}}");
    $(csrf).appendTo(newElement);
    $(selector).after(newElement);
}

//Upload image to form && Clone form
$('#img-upload').click(function(){
  var $el = $(this);
  var isSelected = $el.attr("first-click-done");  //false by default

  if(isSelected != 'true'){
    // first click
    $('#id_form-0-image').trigger('click');
    $('.panel').css('visibility', 'visible');
    $el.attr('first-click-done', true)
  } else {
    cloneForm('div.panel-group:last', 'form');
    $('#id_form-' + (form_count-1) + '-image').trigger('click');
  }
});

//Preview image
$('input[type=file]').change(function() {
  var index = $(this).attr('name').split('-')[1];
  if (this.files && this.files[0]) {
    var reader = new FileReader();
    reader.onload = function(e) {
      $('#image-' + index + '-preview').attr('src', e.target.result);
    }
    reader.readAsDataURL(this.files[0]);
  }
});

//Delete image form
$(".delete_btn").click(function(){
  var form = $(this).parent().parent().parent();
  var form_index = form.find('input').eq(1).attr('name').split('-')[1];
  if (form_count > 1) {
    form.hide('3000', function(){
      $(this).remove();
    });
    
    form_count--;
    $('#id_form-TOTAL_FORMS').val(form_count);
    
    var counter = parseInt(form_index) + 1;
    var next_form = form.next();
    
    // Update form element index
    for (i=counter; i <= form_count; i++) {
      // console.log(i);
      next_form.find(':input').each(function() {
        var name = $(this).attr('name').replace('-' + i + '-','-' + (i-1) + '-');
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id});
      });
      next_form.find('label').each(function() {
        var newFor = $(this).attr('for').replace('-' + i + '-','-' + (i-1) + '-');
        $(this).attr('for', newFor);
      });
      next_form.find('img').each(function() {
        var newId = $(this).attr('id').replace('-' + i + '-','-' + (i-1) + '-');
        $(this).attr('id', newId);
      });
      next_form = next_form.next();
    }       
  }        
});

// Load Subcategories options dependent on Categories selected
$("#id_category").change(function () {
  var url = $("#productForm").attr("data-subcategories-url");  // get the url of the `load_cities` view
  var categoryId = $(this).val();  // get the selected country ID from the HTML input
  $.ajax({                       // initialize an AJAX request
    url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
    data: {
      'category': categoryId       // add the country id to the GET parameters
    },
    success: function (data) {   // `data` is the return of the `load_cities` view function
      $("#id_subcategory").html(data);  // replace the contents of the city input with the data that came from the server
    }
  });

});
{% endblock %}
</script>


{% block content %}
<div class="container">
  <form method="POST" action="" id="productForm" data-subcategories-url="{% url 'seller:ajax_load_subcategories' %}" enctype="multipart/form-data" novalidate> {% csrf_token %}
    <div class="row">
      <div class="col-sm-6">
        <h4><b>CREATE PRODUCT</b></h4>
        <div class="panel panel-default">
          <div class="panel-body">
            {% crispy product_create_form %}
            <input type="submit" value="Add Product" class="btn btn-primary btn-block outline btn-submit">
          </div>
        </div>
      </div>

      <div class="col-sm-6">
        <button type="button" class="btn btn-default btn-block" id="img-upload">Upload Image</button>
        {{ product_image_formset.management_form }}
        <div class="row">
          {% for image_form in product_image_formset %}
            <div class="col-sm-6 panel-group">
              <div class="panel panel-default" style="visibility: hidden">
                <div class="panel-body">
                    <a class="close delete_btn">
                      <span>&times;</span>
                    </a>
                  {{ image_form }}
                  <div class="img-preview-frame">
                    <div class="img-zone"><img id="image-0-preview" src="#" alt="" /></div>
                  </div>
                </div>
              </div>
            </div>
            {% cycle '' '</div><div class="row">' %}
          {% endfor %}
        </div>
      </div>

    </div>
  </form>
</div>

{% endblock %}

src/templates/seller/product_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block style %}
/***********************
  CUSTOM BTN
************************/
.btn {
    padding: 14px 24px;
    border: 0 none;
    font-weight: 700;
    letter-spacing: 1px;
    text-transform: uppercase;
    background: 0 none;
}
.btn:focus, .btn:active:focus, .btn.active:focus {
    outline: 0 none;
}
/***********************
  CUSTOM BUTTON PRIMARY
************************/
.btn-primary {
    background: #0099cc;
    color: #fff;
}
.btn-primary:hover, .btn-primary:focus, .btn-primary:active, .btn-primary.active, .open > .dropdown-toggle.btn-primary {
    background: #33a6cc;
}
.btn-primary:active, .btn-primary.active {
    background: #007299;
    box-shadow: none;
}
.btn.outline {
    background: none;
    padding: 12px 22px;
}
.btn-primary.outline {
    border: 2px solid #0099cc;
    color: #0099cc;
}
.btn-primary.outline:hover, .btn-primary.outline:focus, .btn-primary.outline:active, .btn-primary.outline.active, .open > .dropdown-toggle.btn-primary {
    color: #33a6cc;
    border-color: #33a6cc;
    background: #e7e7e7;
}
.btn-primary.outline:active, .btn-primary.outline.active {
    border-color: #007299;
    color: #007299;
    box-shadow: none;
    background: #e7e7e7;
}
/***********************
  CUSTOM BUTTON DEFAULT
************************/
.btn-default {
    background: #f8f8f8;
    color: #000;
}
.btn-default:hover, .btn-default:focus, .btn-default:active, .btn-default.active, .open > .dropdown-toggle.btn-default {
  background: #f8f8f8;
}
.btn-default:active, .btn-default.active {
    background: #f4f4f4 !important;
}
{% endblock %}

<script>
{% block jquery %}
var form_count = {{ product_image_formset.total_form_count }};
var apr_form_count = form_count; //apparent form count: what the user sees

function cloneForm(selector, prefix) {
    form_count++;
    apr_form_count++;
    var newElement = $(selector).clone(true);
    newElement.addClass("new-image")
    var form_index = newElement.find('input').eq(1).attr('name').split('-')[1];
    newElement.find(':input').each(function() {
        var name = $(this).attr('name').replace('-' + form_index + '-','-' + (form_count-1) + '-');      
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id}).val(''); 
    });
    newElement.find('img').each(function() {
        var newId = $(this).attr('id').replace('-' + form_index + '-','-' + (form_count-1) + '-');
        var src = '#';
        $(this).attr({'id': newId, 'src': src});
    });
    $('#id_' + prefix + '-TOTAL_FORMS').val(form_count);
    //dynamically adding csrf token to the new form added
    var csrf = $('<input/>')
                  .attr("type", "hidden")
                  .attr("name", "csrfmiddlewaretoken")
                  .attr("value", "{{csrf_token}}");
    $(csrf).appendTo(newElement);
    $(selector).after(newElement);
}


//Clone form and trigger image upload btn
$('#img-upload').click(function(){
  if (apr_form_count < 10) {
    cloneForm('div.panel-group:last', 'form');
    $('#id_form-' + (form_count-1) + '-image').trigger('click');
  }
});


//Preview Image
$('input[type=file]').change(function() {
  var index = $(this).attr('name').split('-')[1];
  if (this.files && this.files[0]) {
    var reader = new FileReader();
    reader.onload = function(e) {
      $('#image-' + index + '-preview').attr('src', e.target.result);
    }
    reader.readAsDataURL(this.files[0]);
  }
});


//Delete image form
$(".delete_btn").click(function(){

  var form = $(this).parent().parent().parent();
  var form_index = form.find('input').eq(1).attr('name').split('-')[1];

  if (apr_form_count > 1) {
    new_image = form.hasClass("new-image")
    if (!new_image) {
      $('#id_form-' + form_index + '-DELETE').val('checked');
      form.hide('3000', function(){
        $(this).hide();
      });
      apr_form_count--;
    }
    else {
      form.hide('3000', function(){
        $(this).remove();
      });

      form_count--;
      apr_form_count--;
      $('#id_form-TOTAL_FORMS').val(form_count);
      
      var counter = parseInt(form_index) + 1;
      var next_form = form.next();

      // Update form element index
      for (i=counter; i <= form_count; i++) {
        next_form.find('input').each(function() {
          var name = $(this).attr('name').replace('-' + i + '-','-' + (i-1) + '-');
          var id = 'id_' + name;
          $(this).attr({'name': name, 'id': id});
        });
        next_form.find('img').each(function() {
          var newId = $(this).attr('id').replace('-' + i + '-','-' + (i-1) + '-');
          $(this).attr('id', newId);
        });
        next_form = next_form.next();
      }       
    }
  }        
});

$("#id_category").change(function () {
  var url = $("#productForm").attr("data-subcategories-url");  // get the url of the `load_cities` view
  var categoryId = $(this).val();  // get the selected country ID from the HTML input
  $.ajax({                       // initialize an AJAX request
    url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
    data: {
      'category': categoryId       // add the country id to the GET parameters
    },
    success: function (data) {   // `data` is the return of the `load_cities` view function
      $("#id_subcategory").html(data);  // replace the contents of the city input with the data that came from the server
    }
  });

});

{% endblock %}
</script>


{% block content %}
<div class="container">
  <form method="POST" action="" id="productForm" data-subcategories-url="{% url 'seller:ajax_load_subcategories' %}" enctype="multipart/form-data"> {% csrf_token %}
    <div class="row">
      <div class="col-sm-6">
        <h4><b>EDIT PRODUCT</b></h4>
        <div class="panel panel-default">
          <div class="panel-body">
            {% crispy product_edit_form %}
            <input type="submit" value="Update" class="btn btn-primary btn-block outline btn-submit">
          </div>
        </div>
      </div>

      <div class="col-sm-6">
        <button type="button" class="btn btn-default btn-block" id="img-upload">Add More Image</button>
        {{ product_image_formset.management_form }}
        <div class="row">
          {% for image_form in product_image_formset %}
            <div class="col-sm-6 panel-group">
              <div class="panel panel-default">
                <div class="panel-body">
                    <a class="close delete_btn">
                      <span>&times;</span>
                    </a>
                  {{ image_form }}
                  <div class="img-preview-frame">
                    <div class="img-zone"><img id="image-{{ forloop.counter0 }}-preview" \
                      src="{{ image_form.instance.image_url|default_if_none:'#' }}" alt="" /></div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>

    </div>
  </form>
</div>
{% endblock %}