src/products/urls.py
from django.conf.urls import url

from .views import (
  ProductDetailView,
  ProductListView,
  TagListView,
  TagDetailView,
  )

# app_name = 'utpshare'

# urlpatterns = [
#   path('', ProductListView.as_view(), name='products'),
#   # path('<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
#   path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
# ]


urlpatterns = [
  url(r'^$', ProductListView.as_view(), name='products'),
  url(r'^detail/(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='product_detail'),
  url(r'^tags/$', TagListView.as_view(), name='tags'),
  url(r'^tags/(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='tag_detail'),
]

src/user/urls.py
from django.conf.urls import url, include

from .views import UserDashboardView, OrderList, OrderDetail


urlpatterns = [
    url(r'^$', UserDashboardView.as_view(), name='user_dashboard'),
    url(r'^orders/$', OrderList.as_view(), name='orders'),
    url(r'^orders/(?P<pk>\d+)/$', OrderDetail.as_view(), name='order_detail'),
]

src/utpshare/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include

from products.views import ProductSearchListView, ProductListRedirectView
from user.views import UserDashboardView
from carts.views import CartView, ItemCountView, CheckoutView, CheckoutFinalView
from orders.views import UserAddressCreateView


urlpatterns = [
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^results/', ProductSearchListView.as_view(), name='product_search_list'),
    url(r'^$', ProductListRedirectView.as_view()),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^seller/', include('seller.urls', namespace='seller')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^cart/count/$', ItemCountView.as_view(), name='item_count'),
    url(r'^checkout/$', CheckoutView.as_view(), name='checkout'),
    url(r'^checkout/add_address/$', UserAddressCreateView.as_view(), name='user_address_create'),
    url(r'^checkout/final/$', CheckoutFinalView.as_view(), name='checkout_final'),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from seller.models import SellerAccount


from django_resized import ResizedImageField
import tagulous.models

# Create your models here.

class ProductManager(models.Manager):
  def get_related(self, instance):
    products = self.get_queryset().filter(category = instance.category).exclude(id=instance.id)
    return products

class Product(models.Model):
  seller = models.ForeignKey(SellerAccount, on_delete=models.CASCADE)
  title = models.CharField(max_length=50)
  slug = models.SlugField(blank=True, unique=True)
  description = models.TextField()
  price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
  sale_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
  stock_count = models.PositiveSmallIntegerField(default=1)
  category = models.ForeignKey('Category', blank=True, null=True, on_delete=models.CASCADE)
  subcategory = models.ForeignKey('Subcategory', blank=True, null=True, on_delete=models.CASCADE)
  timestamp = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
  tags = tagulous.models.TagField(to="Tag", null=True, blank=True)

  objects = ProductManager()

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse("products:product_detail", kwargs={"slug": self.slug})

  def get_edit_url(self):
    return reverse("seller:product_update", kwargs={"slug": self.slug})

  def get_image_url(self):
    img = self.productimage_set.first()
    if img:
      return img.image.url
    else:
      return '/static/img/default_image.png'

  def get_html_price(self):
    if self.sale_price is not None:
      html_text = "<span class='sale-price'>%s</span>&emsp;<span class='og-price small'>%s</span>"\
        %(self.sale_price, self.price)
    else:
      html_text = "<span class='price'>%s</span>" %(self.price)
    return mark_safe(html_text) 

  def add_to_cart(self):
    return "%s?item_slug=%s&qty=1" %(reverse("cart"), self.slug)

  def remove_from_cart(self):
    return "%s?item_slug=%s&qty=1&delete_item=True" %(reverse("cart"), self.slug)

def create_slug(instance, new_slug=None):
  # 1st time coming in
  slug = slugify(instance.title)
  # 2nd time coming in
  if new_slug is not None:
    slug = new_slug

  # To check if this slug is unique
  # if slug exists, create a new slug by appending its id to it
  qs = Product.objects.filter(slug=slug)
  exists = qs.exists()
  if exists:
    # qs.first().id is used coz instance not saved yet and instance.id not created
    new_slug = "%s-%s" %(slug, qs.first().id)
    # return a fx so that the loop repeats itself again
    return create_slug(instance, new_slug=new_slug)

  return slug 

def product_pre_save_receiver(sender, instance, *args, **kwargs):
  if not instance.slug:
    instance.slug = create_slug(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)


class Tag(tagulous.models.TagModel):
  class TagMeta:
    force_lowercase = True
    max_count = 10
    get_absolute_url=lambda tag: reverse(
            'products:tag_detail', kwargs={'slug': tag.slug}
        )



# Product Images
def image_upload_to(instance, filename):
  title = instance.product.title
  slug = slugify(title)
  basename, file_extension = filename.split(".")
  new_filename = "%s.%s" %(slug, file_extension)
  return "products/%s/%s" %(slug, new_filename)


import PIL
from PIL import Image
from django.utils.six import StringIO


class ProductImage(models.Model):
  product = models.ForeignKey(Product, on_delete=models.CASCADE)
  image = ResizedImageField(size=[700, 500], upload_to=image_upload_to, blank=True, null=True)
  # size[w, h]

  def __str__(self):
    return self.product.title

  @property
  def image_url(self):
    if self.image and hasattr(self.image, 'url'):
      return self.image.url
    else:
      return '/static/img/default_image.png'


class Category(models.Model):
  title = models.CharField(max_length=50, unique=True)
  slug = models.SlugField(blank=True, unique=True)
  parent_category = models.ForeignKey('self', null=True, blank=True)

  def __str__(self):
    return self.title

def category_pre_save_receiver(sender, instance, *args, **kwargs):
  if not instance.slug:
    instance.slug = slugify(instance.title)

pre_save.connect(category_pre_save_receiver, sender=Category)

class Subcategory(models.Model):
  title = models.CharField(max_length=50, unique=True)
  slug = models.SlugField(blank=True, unique=True)
  category = models.ForeignKey(Category)
  
  def __str__(self):
    return self.title

def subcategory_pre_save_receiver(sender, instance, *args, **kwargs):
  if not instance.slug:
    instance.slug = slugify(instance.title)

pre_save.connect(subcategory_pre_save_receiver, sender=Subcategory)

src/products/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div
from django import forms 
from django.forms import ModelForm, widgets
# from django.forms.formsets import BaseFormSet
from django.forms.models import BaseModelFormSet
from .models import  Product, ProductImage, Subcategory

from .models import ProductImage


class ProductForm(ModelForm):
  class Meta:
    model = Product 
    fields = [
            "title",
            "stock_count",
            "price",
            "category",
            "subcategory",
            "description",
            "tags",
    ]

  def __init__(self, *args, **kwargs):
    super(ProductForm, self).__init__(*args, **kwargs)
    self.fields['subcategory'].queryset = Subcategory.objects.none()
    self.fields['tags'].widget.attrs.update({
        'class': 'tag-field-css-hard-fix',
    })

    if 'category' in self.data:
      try:
        category_id = int(self.data.get('category'))
        self.fields['subcategory'].queryset = Subcategory.objects.filter(category_id=category_id).order_by('title')
      except (ValueError, TypeError):
        pass  # invalid input from the client; ignore and fallback to empty subcategory queryset
    elif self.instance.pk:
      self.fields['subcategory'].queryset = self.instance.category.subcategory_set.order_by('title')

# copied from django/forms/widgets.py
class FileInput(widgets.Input):
    input_type = 'file'
    needs_multipart_form = True

    def render(self, name, value, attrs=None):
        return super(FileInput, self).render(name, None, attrs=attrs)

    def value_from_datadict(self, data, files, name):
        "File widgets take data from FILES, not POST"
        return files.get(name)


# class CustomClearableFileInput(widgets.ClearableFileInput):
#     # only works with django>=1.11
#     template_name = 'custom_clearable_file_input.html'


class ProductImageForm(ModelForm):
  class Meta:
    model = ProductImage
    fields = ['image']
    widgets = {'image': FileInput}

  # def __init__(self, *args, **kwargs):
  #   super(ProductImageForm, self).__init__(*args, **kwargs)
  #   self.fields['image'].label = ""


class BaseProductImageFormSet(BaseModelFormSet):
  def add_fields(self, form, index):
    super(BaseProductImageFormSet, self).add_fields(form, index)
    if self.can_delete:
        form.fields['DELETE'].widget = forms.HiddenInput()

src/products/views.py
from django.db.models import Q
from django.views.generic import View
from django.views.generic.base import RedirectView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import Product, Category, ProductImage, Tag
from analytics.models import TagView
from collections import OrderedDict
import random

# Create your views here.

class ProductListRedirectView(RedirectView):
    permanent = True
    def get_redirect_url(self, *args, **kwargs):
        return "/products"

class TagListView(ListView):
  model = Tag

  def get_context_data(self, *args, **kwargs):
    context = super(TagListView, self).get_context_data(*args, **kwargs)
    context["tag_list"] = self.get_queryset().order_by('-count', '?')
    return context

class TagDetailView(DetailView):
  model = Tag

  def get_context_data(self, *args, **kwargs):
    context = super(TagDetailView, self).get_context_data(*args, **kwargs)
    tag_slug = self.kwargs.get("slug")
    tag = Tag.objects.filter(slug=tag_slug)
    tag_products = Product.objects.filter(tags=tag)
    context["tag_products"] = tag_products
    return context


class ProductDetailView(DetailView):
  model = Product

  def get_context_data(self, *args, **kwargs):
    context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
    
    # get related products by category
    instance = self.get_object()
    tags = instance.tags.all()
    context["related"] = sorted(self.model.objects.get_related(instance)[:6], 
      key=lambda x: random.random())

    if self.request.user.is_authenticated():
      for tag in tags:
        TagView.objects.add_count(self.request.user, tag)
    return context


class ProductListView(ListView):
  model = Product

  def get_context_data(self, **kwargs):
    context = super(ProductListView, self).get_context_data(**kwargs)
    context['category_list'] = Category.objects.all()
    return context 


class ProductSearchListView(ListView):
  model = Product
  template_name = "products/product_search_list.html"

  def get_queryset(self, *args, **kwargs):
    qs = super(ProductSearchListView, self).get_queryset(**kwargs)
    query = self.request.GET.get("q")
    title_matches = qs.filter(Q(title__icontains=query)).order_by("-timestamp")
    description_matches = qs.filter(Q(description__icontains=query)).order_by("-timestamp")
    category_matches = qs.filter(Q(category__title__icontains=query)).distinct().order_by("-timestamp")
    tags_matches = qs.filter(Q(tags__name__icontains=query)).distinct().order_by("-timestamp")
    qs = list(title_matches) + list(description_matches) + list(category_matches) + list(tags_matches)
    return list(OrderedDict.fromkeys(qs))

  def get_context_data(self, *args, **kwargs):
    context = super(ProductSearchListView, self).get_context_data(*args, **kwargs)
    product_list = self.get_queryset()
    context['product_list'] = product_list
    count = len(product_list)
    if count<1:
      context["title"] = "No results found."
    elif count==1:
      context["title"] = "%s %s" %(count, "result found.")
    else:
      context["title"] = "%s %s" %(count, "results found.")
    return context

src/templates/products/product_card.html
<div class="product-card-wrapper">
  <a href="{{ product.get_absolute_url }}">
    {% if card_size == "std" %}
      <div class="card-frame">
        <div class="card-img-frame">
          <img class="card-img" src="{{ product.get_image_url }}">
        </div>
        <div class="card-txt-frame">
          <div class="card-txt-header">{{ product.title }}</div>
          <div class="card-txt-body">
            {{ product.seller.user.username}} &middot; RM {{ product.get_html_price}}&emsp;<span class="price-nego-tag">NEGOTIABLE</span>
            <div class="desc">{{ product.description|truncatewords:25 }}</div>
          </div>
        </div>
      </div>
    {% elif card_size == "sm" %}
      <div class="card-frame-sm">
        <div class="card-img-frame-sm">
          <img class="card-img" src="{{ product.get_image_url }}">
        </div>
        <div class="card-txt-frame-sm">
          <div class="card-txt-header-sm">{{ product.title }}</div>
          <div class="card-txt-body">
            {{ product.seller.user.username}} &middot; RM {{ product.get_html_price}}
          </div>
        </div>
      </div>
    {% endif %}
  </a>
</div>

src/templates/products/product_list.html
{% extends "base.html" %}

{% block style %}
.gallery-nav-bar {
  text-align: center;
  margin-top: 10px;
}
.gallery-title {
  font-size: 2.143em;
}
.gallery-nav-btn-gp {
  display:flex;
  flex-wrap:wrap;
  justify-content:center
}
.gallery-nav-btn {
  padding: 10px;
  background: #3498db;
  color: #fff;
  border: 1px solid #f8f8f8;
  min-width: 90px;
}
.gallery-nav-btn a:link, .gallery-nav-btn a:hover, .gallery-nav-btn a:visited, .gallery-nav-btn a:active {
  color: #fff;
  text-decoration: none;
}

.gallery-nav-btn:hover {
  background: #2980b9;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

/* Links inside the dropdown */
.dropdown-content a {
  float: none;
  color: black;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown:hover .dropdown-content {
  display: block;
}


@media only screen and (max-width: 576px) {
    .gallery-title {
      font-size: 1.2em;
    }
    .gallery-nav-btn {
      padding: 5px;
      font-size: 0.9em;
    }
}
{% endblock %}


<script>
{% block jquery %}
$(".filter-button").click(function(){
    var value = $(this).attr('data-filter');
    
    if(value == "all") {
      $('.filter').show('3000');
    }
    else {
      $(".filter").not('.'+value).hide('1000');
      $('.filter').filter('.'+value).show('3000');
    }
});
{% endblock %}
</script>


{% block content %}
<div class="container">
  <div class="gallery-nav-bar">
    <div class="gallery-title">Product Gallery</div>
    <div class="gallery-nav-btn-gp">
      <div class="gallery-nav-btn filter-button" data-filter="all"><a href="#">All</a></div>
      {% for category in category_list %}
        <div class="dropdown">
          <div class="gallery-nav-btn filter-button" data-filter="{{ category.slug }}">
            <a href="#">{{ category }}</a>
            {% if category.subcategory_set.all %}
              <i class="fa fa-caret-down"></i>
            {% endif %}
          </div>
          <div class="dropdown-content">
            {% for subcategory in category.subcategory_set.all %}
              <div class="gallery-nav-btn filter-button" data-filter="{{ subcategory.slug }}"><a href="#">{{ subcategory }}</a></div>
            {% endfor %}
          </div>
        </div>
      {% endfor %}
    </div>
  </div>

  <div class="tn-set-container">
    {% for category in category_list %}
      {% for product in category.product_set.all %}
        {% include "products/product_thumbnail.html" with product=product %}
      {% endfor %}

      {% for subcategory in category.subcategory_set.all %}
        {% for product in subcategory.product_set.all %}
          {% include "products/product_thumbnail.html" with product=product %}
        {% endfor %}
      {% endfor %}

    {% endfor %}
  </div>
</div>
{% endblock %}

src/templates/products/product_search_list.html
{% extends 'base.html' %}

{% block style %}
.result-title {
  font-size: 1.428em;
  margin-top: 10px;
}
@media only screen and (max-width: 550px) {
  .result-title {
    font-size: 0.9em;
  }
}
{% endblock %}

{% block content %}
<div class="container">
  <div class="result-title">{{title}}</div>
  {% for product in product_list %}
    {% include "products/product_card.html" with product=product card_size="std" %}
  {% endfor %}
</div>
{% endblock %}

src/templates/products/product_thumbnail.html
<div class="tn-frame filter {{ category.slug }} {{ subcategory.slug }}">
  <a href="{{ product.get_absolute_url }}">
    <div class="tn-img-frame">
      <img class="tn-img" src="{{ product.get_image_url }}">
    </div>
    <div class="tn-txt-frame">
      <div class="tn-txt">
        <strong>{{ product.title|truncatechars:50 }}</strong>
        <br/>
        <small>RM {{ product.get_html_price }}</small>
      </div>
    </div>
  </a>
</div>

src/templates/products/tag_detail.html
{% extends 'base.html' %}

{% block style %}
a:link, a:hover, a:visited, a:active {
  text-decoration: none;
}
{% endblock %}

{% block content %}

<div class="container">
  <h4><a href="{% url 'products:tags' %}">< BACK</a></h4>
  <div class="tn-set-container">
    {% for tag_product in tag_products %}
      {% include "products/product_thumbnail.html" with product=tag_product %}
    {% empty %}
      <p>No Products yet.</p>
    {% endfor %}
  </div>
</div>

{% endblock %}

src/templates/products/tag_list.html
{% extends 'base.html' %}

{% block style %}
.tag-list-container {
  display: flex;
  flex-wrap:wrap;
  align-items:flex-start;
}
.tag-list-item {
  flex-basis: 50%;
  margin: 5px 0;
}
{% endblock %}

{% block content %}
<div class="container">
  <h1>Tags</h1>

  <div class="tag-list-container">
    {% for tag in tag_list %}
    <div class="tag-list-item">
      <a href="{{ tag.get_absolute_url }}">{{ tag }}</a> ({{ tag.count }})
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}